# Site settings
title: DCRA Projects
author: 
name: Eastbanc Technologies
description: "DCRA Inspector App user manual on GH-Pages contact@eastbanctech.com"
email: contact@eastbanctech.com

# Build settings
remote_theme: jekyll/minima
